CREATE TABLE GENERS
(
ID INT PRIMARY KEY IDENTITY,
[NAME] VARCHAR(40) NOT NULL,
CONSTRAINT UQ_GENEROS_NOME UNIQUE ([NAME])
)

CREATE TABLE CLIENTS
(
ID INT PRIMARY KEY IDENTITY,
[NAME] VARCHAR(50) NOT NULL,
CPF CHAR(14) NOT NULL UNIQUE,
EMAIL VARCHAR(50) NOT NULL UNIQUE,
BIRTH_DAY DATE NOT NULL,
ISACTIVE BIT NOT NULL
CONSTRAINT UQ_CLI_CPF UNIQUE (CPF),
CONSTRAINT UQ_CLI_EMAIL UNIQUE (EMAIL)
)

CREATE TABLE FILMS
(
ID INT PRIMARY KEY IDENTITY,
[NAME] VARCHAR(100) NOT NULL,
RELEASEDATE DATE NOT NULL,
[CLASSIFICATION] INT NOT NULL,
DURATION INT NOT NULL,
GENERID INT NOT NULL REFERENCES GENERS
)

CREATE TABLE FUNCTIONARIES
(
ID INT PRIMARY KEY IDENTITY,
[NAME] VARCHAR(100) NOT NULL,
BIRTH_DATE DATE NOT NULL,
CPF CHAR(14) NOT NULL UNIQUE,
EMAIL VARCHAR(50) NOT NULL UNIQUE,
TELEPHONE VARCHAR(15) NOT NULL,
[PASSWORD] VARCHAR(100) NOT NULL,
ISACTIVE BIT NOT NULL
CONSTRAINT UQ_FUN_CPF UNIQUE (CPF),
CONSTRAINT UQ_FUN_EMAIL UNIQUE (EMAIL)
)

CREATE TABLE LOCACOES
(
ID INT PRIMARY KEY IDENTITY,
CLIENT INT NOT NULL,
FUNCTIONARY INT NOT NULL,
PRECO FLOAT NOT NULL,
DATALOCACAO DATETIME2 NOT NULL,
DATADEVOLUCAOPREVISTA DATETIME2 NOT NULL,
DATADEVOLUCAO DATETIME2 NULL,
MULTA FLOAT NOT NULL,
FOIPAGO BIT NOT NULL,
CONSTRAINT FK_LOCACOES_CLIENT FOREIGN KEY (CLIENT) REFERENCES CLIENTS,
CONSTRAINT FK_LOCACOES_FUNCTIONARY FOREIGN KEY (FUNCTIONARY) REFERENCES FUNCTIONARIES
)

CREATE TABLE LOCACOES_FILMES
(
LOCACAOID INT REFERENCES LOCACOES,
FILMEID	INT REFERENCES FILMS,
PRIMARY KEY (LOCACAOID, FILMEID)
)

SELECT * FROM FUNCTIONARIES

UPDATE FILMS SET [CLASSIFICATION] = 16
WHERE [CLASSIFICATION] = 4
